name: tdxhydrorapid
channels:
- conda-forge
- defaults
dependencies:
  - dask-geopandas
  - libgdal-arrow-parquet
  - geopandas>=1.0
  - natsort
  - netcdf4
  - networkx
  - numpy
  - openpyxl
  - pandas
  - shapely>=2
  - pyarrow
  - pyproj
  - pyogrio
  - python>=3.11
  - dask
  - xarray
  - scikit-learn
