name: hydrography
channels:
- conda-forge
- defaults
dependencies:
  - geopandas>=1.0
  - natsort
  - netcdf4
  - networkx
  - numpy
  - openpyxl
  - pandas
  - shapely>=2
  - pyarrow
  - pyproj
  - python>=3.14
  - dask
  - xarray
